addons:
   apt:
      sources:
         - r-packages-trusty
      packages:
         - build-essential
         - libasound2
         - libbluetooth3
         - libc6
         - libpam0g
         - libxcb-keysyms1
         - libxcb-shape0
         - libxcb1
         - libvlc5
         - libbulletcollision2.81
         - libbulletdynamics2.81
         - libbulletsoftbody2.81
         - libdbus-1-3
         - libfontconfig1
         - libfreetype6
         - libfribidi0
         - libgcc1
         - libgif4
         - libgl1-mesa-glx
         - libglib2.0-0
         - libgstreamer-plugins-base1.0-0
         - libgstreamer1.0-0
         - libharfbuzz0b
         - libjpeg8
         - liblinearmath2.81
         - libluajit-5.1-2
         - libmount1
         - libpng12-0
         - libpulse0
         - libsndfile1
         - libssl1.0.0
         - libstdc++6
         - libtiff5
         - libudev1
         - libwebp5
         - libx11-6
         - libxcomposite1
         - libxcursor1
         - libxdamage1
         - libxext6
         - libxfixes3
         - libxi6
         - libxinerama1
         - libxp6
         - libxrandr2
         - libxrender1
         - libxss1
         - libxtst6
         - zlib1g
         - libfreetype6
         - libgcc1
         - libluajit-5.1-2
         - libpng12-0
         - libcairo2
         - libglib2.0-0
         - libpoppler44
         - libraw9
         - librsvg2-2
         - libspectre1
         - zlib1g
         - autopoint
         - doxygen
         - check
         - libssl-dev
         - libjpeg-dev
         - luajit
         - libluajit-5.1-dev
         - libfreetype6-dev
         - libfontconfig1-dev
         - libfribidi-dev
         - libx11-dev
         - libcogl-gles2-dev
         - libgif-dev
         - libtiff5-dev
         - libgstreamer-plugins-base1.0-dev
         - libdbus-1-dev
         - libmount-dev
         - libblkid-dev
         - libpulse-dev
         - libsndfile1-dev
         - libxinerama-dev
         - libxrender-dev
         - libxrandr-dev
         - libxfixes-dev
         - libxdamage-dev
         - libxcursor-dev
         - libxcomposite-dev
         - libxss-dev
         - libxext-dev
         - libxkbfile-dev
         - libxtst-dev
         - libxcb1-dev
         - libxcb-shape0-dev
         - libxcb-keysyms1-dev
         - libbullet-dev
         - vlc
         - libvlc-dev
         - autoconf
         - libtool
         - libpng-dev

language: c
script: mkdir -p build && cd build && cmake .. && make
compiler: gcc

before_script:
   - git clone git://git.enlightenment.org/core/efl.git && cd efl && ./autogen.sh --prefix=/usr && make && sudo make install && sudo ldconfig 

