addons:
   apt:
      sources:
         - r-packages-trusty
      packages:
         - build-essential
         - libasound2
         - libbluetooth3
         - libc6
         - libpam0g
         - libxcb-keysyms1
         - libxcb-shape0
         - libxcb1
         - libvlc5
         - libdbus-1-3
         - libfontconfig1
         - libfreetype6
         - libfribidi0
         - libgcc1
         - libgif4
         - libgl1-mesa-glx
         - libglib2.0-0
         - libjpeg8
         - libmount1
         - libpng12-0
         - libpulse0
         - libsndfile1
         - libssl1.0.0
         - libstdc++6
         - libx11-6
         - libxcomposite1
         - libxcursor1
         - libxdamage1
         - libxext6
         - libxfixes3
         - libxi6
         - libxinerama1
         - libxrandr2
         - libxrender1
         - libxss1
         - libxtst6
         - zlib1g
         - libfreetype6
         - libgcc1
         - libpng12-0
         - libcairo2
         - libglib2.0-0
         - librsvg2-2
         - zlib1g
         - autopoint
         - doxygen
         - check
         - libssl-dev
         - libjpeg-dev
         - luajit
         - pkg-config
         - libfreetype6-dev
         - libfontconfig1-dev
         - libfribidi-dev
         - libx11-dev
         - libgif-dev
         - libpulse-dev
         - libsndfile1-dev
         - libxinerama-dev
         - libxrender-dev
         - libxrandr-dev
         - libxfixes-dev
         - libxdamage-dev
         - libxcursor-dev
         - libxcomposite-dev
         - libxss-dev
         - libxext-dev
         - libxtst-dev
         - libxcb1-dev
         - libxcb-shape0-dev
         - libxcb-keysyms1-dev
         - vlc
         - libvlc-dev
         - autoconf
         - libtool
         - libpng-dev
         - libluajit-5.1-dev

   coverity_scan:
      project:
         name: jeanguyomarch/war2tools
         version: 0.99.0
         description: Warcraft II Utilities

      notification_email: jean.guyomarch@gmail.com
      build_command_prepend: cmake .
      build_command: make
      branch_pattern: coverity_scan

language: c
script: mkdir -p build && cd build && cmake .. && make
compiler: gcc

before_script:
   - wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.tar.gz
   - tar -xf cmake-3.4.1-Linux-x86_64.tar.gz
   - sudo bash -c "cp -r cmake-3.4.1-Linux-x86_64/* /usr/"
   - cmake --version
   - wget http://download.enlightenment.org/rel/libs/efl/efl-1.16.0.tar.gz
   - tar -xf efl-1.16.0.tar.gz
   - cd efl-1.16.0 && ./configure --prefix=/usr --disable-physics --disable-audio --disable-libmount --disable-libeeze --disable-gstreamer --disable-gstreamer1 --enable-i-really-know-what-i-am-doing-and-that-this-will-probably-break-things-and-i-will-fix-them-myself-and-send-patches-aba && make && sudo make install && sudo ldconfig && cd ..

